FALLBACK fallback Contract 1 1 INNCALL NULL
FUN1 void NULL 1 0 NULL NULL
FUN2 void FALLBACK 1 4 FALLCALL NULL
FUN3 void NULL 1 0 NULL NULL
VAR0 FUN1 3 INNFUN ASSIGN
VAR1 FUN2 3 INNFUN BOOL
VAR2 FUN3 3 INNFUN BOOL
